version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: &schedule
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule: *schedule
