version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: &schedule
      interval: "weekly"
    groups: &groups
      dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule: *schedule
    groups: *groups
