fn_params_layout = "Vertical"
max_width = 120
use_field_init_shorthand = true
use_try_shorthand = true

# To run `rustup run nightly rustfmt` correctly
edition = "2021"
# Unstable
# https://github.com/rust-lang/rustfmt/issues/3348
format_code_in_doc_comments = true
# https://github.com/rust-lang/rustfmt/issues/5083
group_imports = "StdExternalCrate"
# https://github.com/rust-lang/rustfmt/issues/4991
imports_granularity = "Crate"
# https://github.com/rust-lang/rustfmt/issues/3361
imports_layout = "Vertical"
