name: ${APP_NAME}

services:
  database:
    container_name: database
    image: postgres:16.0-alpine3.18
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "--username=${DATABASE_USER}"]
      interval: 1s
      timeout: 30s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.2.2-alpine3.18
    ports:
      - ${REDIS_PORT}:6379
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 1s
    #   timeout: 30s
    #   retries: 3

volumes:
  database_data:
