services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: prorub
      POSTGRES_USER: prorub
    ports:
      - 5432:5432

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  victoriametrics:
    image: victoriametrics/victoria-metrics:stable
    restart: always
    ports:
      - 8428:8428

  vmagent:
    image: victoriametrics/vmagent:stable
    restart: always
    ports:
      - 8429:8429
    command: -promscrape.config=/etc/vmagent/vmagent.yaml -remoteWrite.url=http://victoriametrics:8428/api/v1/write
    volumes:
      - ./vmagent.yaml:/etc/vmagent/vmagent.yaml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   environment:
  #     KEYCLOAK_ADMIN: prorub
  #     KEYCLOAK_ADMIN_PASSWORD: prorub
  #   ports:
  #     - 8081:8080
  #   command: start-dev

  # minio:
  #   image: minio/minio:latest
  #   environment:
  #     - MINIO_ROOT_USER=prorub
  #     - MINIO_ROOT_PASSWORD=prorubpro
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: server /data --console-address ":9001"
